//go:build !co

// Code generated by github.com/goghcrow/go-co DO NOT EDIT.
package sched

import (
	ʂɘʠ "github.com/goghcrow/go-co/seq"
	"sync"
)

type (
	Continuation func(v any, err error)
	Async        func(Continuation)
	Sched        struct {
		val any
		err error
	}
)

func Co(co func(s *Sched) ʂɘʠ.Iterator[Async]) {
	sched := &Sched{}
	sched.run(co)
}

var wg = &sync.WaitGroup{}

func DeferMain() {
	wg.Wait()
}

func (s *Sched) run(co func(s *Sched) ʂɘʠ.Iterator[Async]) {
	it := co(s)

	var recur func()
	recur = func() {
		if it.MoveNext() {
			it.Current()(func(v any, err error) {
				s.Send(v, err)
				recur()
			})
			return
		}
		wg.Done()
	}

	wg.Add(1)
	recur()
}

func (s *Sched) Send(v any, err error) {
	s.val = v
	s.err = err
}

func (s *Sched) GetReceive() (any, error) {
	return s.val, s.err
}
