//go:build !co

// Code generated by github.com/goghcrow/go-co DO NOT EDIT.
package sched

import (
	ʂɘʠ "github.com/goghcrow/go-co/seq"
	"sync"
)

type (
	Act              func()
	Act1[T1 any]     func(T1)
	Act2[T1, T2 any] func(T1, T2)

	Continuation     Act
	OnCompleted      Act1[Continuation]
	AsyncFn[Ctx any] Act2[Ctx, Continuation]
)

var wg = &sync.WaitGroup{}

func DeferMain() {
	wg.Wait()
}

func Await[T any](ctx T, f AsyncFn[T]) OnCompleted {
	return func(k Continuation) {
		f(ctx, k)
	}
}

func AsyncRun(f func() ʂɘʠ.Iterator[OnCompleted]) {
	it := f()

	var recur func()
	recur = func() {
		if it.MoveNext() {
			it.Current()(recur)
			return
		}
		wg.Done()
	}

	wg.Add(1)
	recur()
}
